services:
  magic:
    # image: mageai/mageai:latest
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./mage/Dockerfile
      args:
        - USER_CODE_PATH=${USER_CODE_PATH}
    environment:
      ENV: ${ENV}
    ports:
      - 6789:6789
    volumes:
      - ./mage:/home/src/
      - ./dbt/sf_crime_stats:/home/src/sf-crime-stats/dbt/sf_crime_stats_dbt
      - ./terraform/envs/dev/keys:/home/src/keys
    restart: on-failure:5s