version: 0.1.1
default:
  GOOGLE_SERVICE_ACC_KEY_FILEPATH: "/home/mage/sf-crime-stats-mage/secrets/gcp_keys_dev.json"
  GOOGLE_LOCATION: US # Optional

dev:
  GOOGLE_SERVICE_ACC_KEY_FILEPATH: "/secrets/bigquery/bigquery-credentials-dev"
  GOOGLE_LOCATION: US

prod:
  GOOGLE_SERVICE_ACC_KEY_FILEPATH: "/secrets/bigquery/bigquery-credentials-prod"
  GOOGLE_LOCATION: US