version: 0.1.1
default:
  GOOGLE_SERVICE_ACC_KEY_FILEPATH: "/home/src/secrets/gcp_keys.json"
  GOOGLE_LOCATION: US # Optional

dev:
  GOOGLE_SERVICE_ACC_KEY_FILEPATH: "/secrets/bigquery/bigquery-credentials-dev.json"
  GOOGLE_LOCATION: US

prod:
  GOOGLE_SERVICE_ACC_KEY_FILEPATH: "/secrets/bigquery/bigquery-credentials-prod.json"
  GOOGLE_LOCATION: US