version: 2

models:
  - name: fact_incidents
    description: > 
      Contains criminal incidents reported to the San Francisco Police Department (SFPD)

  - name: dim_incident_details
    description: > 
      Contains descriptive details about criminal incidents

  - name: dim_report_details
    description: >
      Contains report information

  - name: dim_location
    description: >
      Contains San Francisco location information

  - name: dim_incident_date
    description: >
      Contains date information for analysis using the date an incident occurred
  
  - name: dim_report_date
    description: >
      Contains date information for analysis using the date an incident was reported
