triggers:
- description: null
  envs: []
  last_enabled_at: 2025-06-18 23:22:54.999142
  name: sfpd_incidents_daily_trigger
  pipeline_uuid: ingest_sfpd_incidents_daily
  schedule_interval: 30 17 * * *
  schedule_type: time
  settings:
    landing_time_enabled: false
  sla: null
  start_time: 2025-06-01 17:30:00
  status: inactive
  token: 7a9183a19c6342028144df8426a3939f
  variables:
    config_profile: prod
    gcp_project_id: sf-crime-stats-455819
    gcs_bucket: sf-crime-stats-terra-bucket-kd
    input_date: YYYY-MM-DD
- description: null
  envs: []
  last_enabled_at: 2025-06-04 22:18:34.265543
  name: Backfill_historical_load
  pipeline_uuid: ingest_sfpd_incidents_daily
  schedule_interval: '@once'
  schedule_type: null
  settings: null
  sla: null
  start_time: 2025-06-04 22:14:20.122934
  status: inactive
  token: 8aad68bc04c541e39d54093edfda0e05
  variables:
    config_profile: dev
    gcp_project_id: sf-crime-stats-455819
    gcs_bucket: sf-crime-stats-terra-bucket-kd
    input_date: YYYY-MM-DD
