sf_crime_stats:
  target: dev # Default target
  outputs:
    default:
      type: bigquery
      method: service-account
      project: sf-crime-stats-455819
      dataset: dbt_kd
      threads: 4 # Must be a value of 1 or greater
      keyfile: /home/mage/sf-crime-stats-mage/secrets/gcp_keys_dev.json

    dev:
      type: bigquery
      method: service-account
      project: sf-crime-stats-455819
      dataset: sf_crime_stats_dev
      threads: 4 # Must be a value of 1 or greater
      keyfile: /home/mage/sf-crime-stats-mage/secrets/gcp_keys_dev.json

    prod:
      type: bigquery
      method: service-account
      project: sf-crime-stats-455819
      dataset: sf_crime_stats_prod
      threads: 4 # Must be a value of 1 or greater
      keyfile: /home/mage/sf-crime-stats-mage/secrets/gcp_keys_prod.json